# 06 — Model Evaluation

Compares three Bible reference extractors on a held-out gold test set.

| Model | Class | Role |
|-------|-------|------|
| **Regex** | `BibleReferenceAnnotator` | Baseline |
| **CRF** | `CRFBibleReferenceExtractor` | Sequence labeller |
| **IndoBERT NER** | `BibleReferenceExtractor` | Fine-tuned transformer |

---

### Evaluation Protocol

Metrics are computed at two complementary levels.

**Span-level** — how well predicted text spans align with gold spans:
- *Exact match* — predicted span must match the gold span character-for-character
- *Partial match* — predicted and gold spans must overlap by ≥ 50% of the shorter span

**Structure-level** — correctness after parsing spans into structured fields (`book_start`, `start_chapter`, `book_end`, `end_chapter`):
- *Exact match only* — all four fields must agree with the gold annotation; no partial credit

Precision, Recall, and F1 are reported for each level.

---
## 1. Setup

In [1]:
import json
import sys
import warnings
import numpy as np
from pathlib import Path
from typing import Any, Dict, List


import pandas as pd

warnings.filterwarnings('ignore')

root = Path('..').resolve()
sys.path.append(str(root / 'src'))

from bible import load_bible_data
from core.config import DATA_DIR, MODEL_DIR, MODEL_PATH, CONFIG_PATH

CRF_MODEL_PATH = MODEL_DIR / 'crf-bible-ner.pkl'
W2V_MODEL_PATH = MODEL_DIR / 'word2vec-bible.model'

print('Setup complete.')

Setup complete.

---
## 2. Load Data

Load the gold test set and model artifacts needed for evaluation.

In [2]:
bible_data = load_bible_data()
print(f'Loaded {len(bible_data['books'])} books.')

Loaded 66 books.

In [3]:
with open(DATA_DIR / 'gold_data.json', 'r', encoding='utf-8') as f:
    gold_data = json.load(f)

df_gold = pd.DataFrame(gold_data)[['text', 'spans', 'structures']]
print(f'Test set: {len(df_gold)} messages, '
      f'{df_gold['structures'].apply(len).sum()} total gold references')
df_gold.head()

Test set: 80 messages, 113 total gold references

,text,spans,structures
0,2 Yuhanes done,"[{'start': 0, 'end': 9, 'label': 'BIBLE_REF', ...","[{'book_start': '2 Yuhanes', 'start_chapter': ..."
1,Why 1-2 done,"[{'start': 0, 'end': 7, 'label': 'BIBLE_REF', ...","[{'book_start': 'Why', 'start_chapter': 1, 'bo..."
2,Efs1-2 done,"[{'start': 0, 'end': 6, 'label': 'BIBLE_REF', ...","[{'book_start': 'Efs', 'start_chapter': 1, 'bo..."
3,_Bil 1-2_ ✓,"[{'start': 1, 'end': 8, 'label': 'BIBLE_REF', ...","[{'book_start': 'Bil', 'start_chapter': 1, 'bo..."
4,Gal 3-6 done,"[{'start': 0, 'end': 7, 'label': 'BIBLE_REF', ...","[{'book_start': 'Gal', 'start_chapter': 3, 'bo..."

---
## 3. Evaluation Protocol

Matching functions used across all three models — span exact, span partial (≥ 50% overlap), and structure exact.

In [4]:
def span_exact_match(pred: Dict, gold: Dict) -> bool:
    """True if predicted span has identical start, end, label."""
    return (pred['start'] == gold['start']
            and pred['end'] == gold['end']
            and pred.get('label') == gold.get('label'))

def span_overlap_ratio(pred: Dict, gold: Dict) -> float:
    """Intersection / length-of-shorter span."""
    lo = max(pred['start'], gold['start'])
    hi = min(pred['end'], gold['end'])
    intersection = max(0, hi - lo)
    shorter = min(pred['end'] - pred['start'], gold['end'] - gold['start'])
    return intersection / shorter if shorter > 0 else 0.0

def span_partial_match(pred: Dict, gold: Dict,threshold: float = 0.5) -> bool:
    return span_overlap_ratio(pred, gold) >= threshold

def struct_exact_match(pred: Dict, gold: Dict) -> bool:
    """All four fields must be identical."""
    return (
        (pred.get('book_start') or '').lower() == (gold.get('book_start') or '').lower()
        and pred.get('start_chapter') == gold.get('start_chapter')
        and (pred.get('book_end') or '').lower() == (gold.get('book_end') or '').lower()
        and pred.get('end_chapter') == gold.get('end_chapter')
    )

def compute_prf(
    all_preds: List[List[Dict]],
    all_golds: List[List[Dict]],
    match_fn,
) -> Dict[str, float]:
    """Micro-averaged P / R / F1 using a greedy one-to-one matching strategy."""
    tp = fp = fn = 0

    for preds, golds in zip(all_preds, all_golds):
        matched_gold = set()
        matched_pred = set()

        # Greedy matching: each pred can match at most one gold
        for pi, pred in enumerate(preds):
            for gi, gold in enumerate(golds):
                if gi in matched_gold:
                    continue
                if match_fn(pred, gold):
                    tp += 1
                    matched_gold.add(gi)
                    matched_pred.add(pi)
                    break

        fp += len(preds) - len(matched_pred)
        fn += len(golds) - len(matched_gold)

    precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0
    f1 = (2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0.0)

    return {'precision': precision, 'recall': recall, 'f1': f1,
            'tp': tp, 'fp': fp, 'fn': fn}


def evaluate_model(
    name: str,
    pred_spans,
    pred_structs,
    gold_spans,
    gold_structs,
) -> Dict[str, Any]:
    """Run all four metric combinations for a single model."""
    return {
        'model': name,
        'span_exact': compute_prf(pred_spans, gold_spans, span_exact_match),
        'span_partial': compute_prf(pred_spans, gold_spans, span_partial_match),
        'struct_exact': compute_prf(pred_structs, gold_structs, struct_exact_match),
    }


print('Helpers defined.')

Helpers defined.

---
## 4. Model 1 — Regex Baseline

Rule-based extractor. Sets the performance floor for the other two models.

In [5]:
from extraction.rule_based import BibleRegexBuilder, RuleBasedExtractor
from services import preprocess

regex_builder = BibleRegexBuilder(bible_data)
regex_parser = RuleBasedExtractor(regex_builder.patterns)

regex_spans = []
regex_structs = []

for row in gold_data:
    text = preprocess(row['text'])
    spans = regex_parser.extract_ner_spans(text)
    structs_raw = regex_parser.extract_structure(text)
    regex_spans.append(spans)
    regex_structs.append(structs_raw)

print(f'Regex extracted spans per message: '
      f'{[len(s) for s in regex_spans]}')

Regex extracted spans per message: [0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 10, 3, 2, 2, 1, 1, 1, 1, 1, 1, 3, 2, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 3, 0, 0, 1, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

---
## 5. Model 2 — CRF

CRF sequence labeller with Word2Vec similarity features.

In [6]:
crf_spans = []
crf_structs = []
CRF_AVAILABLE = CRF_MODEL_PATH.exists() and W2V_MODEL_PATH.exists()

if CRF_AVAILABLE:
    from extraction.crf import CRFBibleReferenceExtractor

    crf_extractor = CRFBibleReferenceExtractor(
        crf_path=CRF_MODEL_PATH,
        w2v_path=W2V_MODEL_PATH
    )

    for row in gold_data:
        text = preprocess(row['text'])
        spans = crf_extractor.extract_ner_spans(text)
        structs_raw = crf_extractor.extract_structure(text)
        crf_spans.append(spans)
        crf_structs.append(structs_raw)

    print(f'CRF spans per message: {[len(s) for s in crf_spans]}')
else:
    print(f'CRF artefacts not found at {CRF_MODEL_PATH} — '
          'filling with empty predictions (all zeros).')
    crf_spans = [[] for _ in gold_data]
    crf_structs = [[] for _ in gold_data]

2026-04-29 09:27:33 | INFO     | bible_pipeline.extraction.crf_extractor | CRFBibleReferenceExtractor ready — model: crf-bible-ner.pkl | W2V vocab: 1462
CRF spans per message: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 2, 2, 1, 1, 1, 1, 1, 0, 3, 2, 2, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 0, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

---
## 6. Model 3 — IndoBERT NER

Fine-tuned transformer extractor.

In [7]:
ner_spans = []
ner_structs = []
NER_AVAILABLE = MODEL_PATH.exists()

if NER_AVAILABLE:
    from extraction.indobert import BibleReferenceExtractor

    ner_extractor = BibleReferenceExtractor(
        saved_path=MODEL_PATH,
        config_path=CONFIG_PATH,
    )

    # Batch inference for efficiency
    texts = [preprocess(row['text']) for row in gold_data]
    ner_spans = ner_extractor.extract_batch(texts, return_spans=True)
    ner_structs = ner_extractor.extract_batch(texts, return_spans=False)

    print(f'NER spans per message: {[len(s) for s in ner_spans]}')
else:
    print(f'NER checkpoint not found at {MODEL_PATH} — '
          'filling with empty predictions (all zeros).')
    ner_spans = [[] for _ in gold_data]
    ner_structs = [[] for _ in gold_data]

2026-04-29 09:27:34 | INFO     | bible_pipeline.extraction.extractor | Loading model from saved path: C:\one one\Desktop\bible_reading_recap_nlp\models\indobert-bible-ner-v4

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

NER spans per message: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 10, 3, 2, 2, 1, 1, 1, 1, 1, 1, 3, 2, 3, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

---
## 7. Results Summary

Aggregate P / R / F1 across all models and metric levels. Highlights the best-performing model and practical trade-offs between interpretability, latency, and accuracy.

In [8]:
gold_spans = [row['spans'] for row in gold_data]
gold_structs = [row['structures'] for row in gold_data]

print(f'Total gold spans     : {sum(len(s) for s in gold_spans)}')
print(f'Total gold structures: {sum(len(s) for s in gold_structs)}')

Total gold spans     : 99
Total gold structures: 113

In [ ]:
results = [
    evaluate_model('Regex (baseline)', regex_spans,  regex_structs, gold_spans, gold_structs),
    evaluate_model('CRF', crf_spans, crf_structs, gold_spans, gold_structs),
    evaluate_model('IndoBERT NER', ner_spans, ner_structs, gold_spans, gold_structs),
]

rows = []
METRIC_KEYS = ['span_exact', 'span_partial', 'struct_exact']
METRIC_LABELS = {
    'span_exact': 'Span — Exact',
    'span_partial': 'Span — Partial',
    'struct_exact': 'Structure — Exact',
}

for res in results:
    for mk in METRIC_KEYS:
        m = res[mk]
        rows.append({
            'Model': res['model'],
            'Metric': METRIC_LABELS[mk],
            'Precision': round(m['precision'], 4),
            'Recall': round(m['recall'], 4),
            'F1': round(m['f1'], 4),
            'TP': m['tp'],
            'FP': m['fp'],
            'FN': m['fn'],
        })

df_eval = pd.DataFrame(rows)
df_eval

              Model             Metric  Precision  Recall      F1   TP  FP  FN
0  Regex (baseline)       Span — Exact     0.7536  0.5253  0.6190   52  17  47
1  Regex (baseline)     Span — Partial     0.9710  0.6768  0.7976   67   2  32
2  Regex (baseline)  Structure — Exact     0.8696  0.5310  0.6593   60   9  53
3               CRF       Span — Exact     0.8837  0.7677  0.8216   76  10  23
4               CRF     Span — Partial     0.9884  0.8586  0.9189   85   1  14
5               CRF  Structure — Exact     0.9208  0.8230  0.8692   93   8  20
6      IndoBERT NER       Span — Exact     0.9091  0.9091  0.9091   90   9   9
7      IndoBERT NER     Span — Partial     1.0000  1.0000  1.0000   99   0   0
8      IndoBERT NER  Structure — Exact     0.9381  0.9381  0.9381  106   7   7

---
## 8. Error Analysis

Inspect false positives and false negatives per model to surface systematic failure patterns — e.g. missed abbreviations, partial span boundaries, or cross-book range confusion.

In [10]:
def error_analysis(name, pred_structs, gold_structs, gold_data, match_fn):
    print(f"{'='*60}")
    print(f" {name}")
    print(f"{'='*60}")

    for i, (preds, golds, row) in enumerate(zip(pred_structs, gold_structs, gold_data)):
        matched_gold = set()
        matched_pred = set()

        for pi, pred in enumerate(preds):
            for gi, gold in enumerate(golds):
                if gi in matched_gold:
                    continue
                if match_fn(pred, gold):
                    matched_gold.add(gi)
                    matched_pred.add(pi)
                    break
        
        fps = [preds[pi] for pi in range(len(preds)) if pi not in matched_pred]
        fns = [golds[gi] for gi in range(len(golds)) if gi not in matched_gold]

        if fps or fns:
            print(f"\n[{i}] \"{row['text']}\"")
            for fp in fps:
                print(f"  FP (wrong pred) : {fp}")
            for fn in fns:
                print(f"  FN (missed gold): {fn}")

In [11]:
# span error analysis
error_analysis('Regex (baseline)', regex_spans, gold_spans, gold_data, span_exact_match)
error_analysis('CRF', crf_spans, gold_spans, gold_data, span_exact_match)
error_analysis('IndoBERT NER', ner_spans, gold_spans, gold_data, span_exact_match)

============================================================
 Regex (baseline)
============================================================

[0] "2 Yuhanes done"
  FN (missed gold): {'start': 0, 'end': 9, 'label': 'BIBLE_REF', 'text': '2 Yuhanes'}

[2] "Efs1-2 done"
  FP (wrong pred) : {'start': 0, 'end': 7, 'label': 'BIBLE_REF', 'text': 'Efs 1-2'}
  FN (missed gold): {'start': 0, 'end': 6, 'label': 'BIBLE_REF', 'text': 'Efs1-2'}

[3] "_Bil 1-2_ ✓"
  FP (wrong pred) : {'start': 2, 'end': 9, 'label': 'BIBLE_REF', 'text': 'Bil 1-2'}
  FN (missed gold): {'start': 1, 'end': 8, 'label': 'BIBLE_REF', 'text': 'Bil 1-2'}

[5] "2 Koruntus done"
  FN (missed gold): {'start': 0, 'end': 10, 'label': 'BIBLE_REF', 'text': '2 Koruntus'}

[12] "Ibrani 11-Yakobus 1; 2-3; 4-5"
  FP (wrong pred) : {'start': 0, 'end': 19, 'label': 'BIBLE_REF', 'text': 'Ibrani 11-Yakobus 1'}
  FN (missed gold): {'start': 0, 'end': 29, 'label': 'BIBLE_REF', 'text': 'Ibrani 11-Yakobus 1; 2-3; 4-5'}

[15] "1 Kor 1,2,3,4,5 done"
  FP (wrong pred) : {'start': 0, 'end': 7, 'label': 'BIBLE_REF', 'text': '1 Kor 1'}
  FN (missed gold): {'start': 0, 'end': 15, 'label': 'BIBLE_REF', 'text': '1 Kor 1,2,3,4,5'}

[16] "Mazmur 1, 23, 91 selesai"
  FP (wrong pred) : {'start': 0, 'end': 8, 'label': 'BIBLE_REF', 'text': 'Mazmur 1'}
  FN (missed gold): {'start': 0, 'end': 16, 'label': 'BIBLE_REF', 'text': 'Mazmur 1, 23, 91'}

[17] "Mat 5, 6, 7 done"
  FP (wrong pred) : {'start': 0, 'end': 5, 'label': 'BIBLE_REF', 'text': 'Mat 5'}
  FN (missed gold): {'start': 0, 'end': 11, 'label': 'BIBLE_REF', 'text': 'Mat 5, 6, 7'}

[18] "Kej 1,3,5,7 selesai"
  FP (wrong pred) : {'start': 0, 'end': 5, 'label': 'BIBLE_REF', 'text': 'Kej 1'}
  FN (missed gold): {'start': 0, 'end': 11, 'label': 'BIBLE_REF', 'text': 'Kej 1,3,5,7'}

[26] "1-3 Yoh done"
  FP (wrong pred) : {'start': 2, 'end': 7, 'label': 'BIBLE_REF', 'text': '3 Yoh'}
  FN (missed gold): {'start': 0, 'end': 7, 'label': 'BIBLE_REF', 'text': '1-3 Yoh'}

[27] "1-2 Kor done"
  FP (wrong pred) : {'start': 2, 'end': 7, 'label': 'BIBLE_REF', 'text': '2 Kor'}
  FN (missed gold): {'start': 0, 'end': 7, 'label': 'BIBLE_REF', 'text': '1-2 Kor'}

[28] "1-2 Samuel selesai"
  FP (wrong pred) : {'start': 2, 'end': 10, 'label': 'BIBLE_REF', 'text': '2 Samuel'}
  FN (missed gold): {'start': 0, 'end': 10, 'label': 'BIBLE_REF', 'text': '1-2 Samuel'}

[31] "Kej 5-6 done
7-8 done
9-10 done"
  FN (missed gold): {'start': 13, 'end': 16, 'label': 'BIBLE_REF', 'text': '7-8'}
  FN (missed gold): {'start': 22, 'end': 26, 'label': 'BIBLE_REF', 'text': '9-10'}

[34] "Msm 13 - 14 done"
  FN (missed gold): {'start': 0, 'end': 11, 'label': 'BIBLE_REF', 'text': 'Msm 13 - 14'}

[35] "Ayun 15-16 done"
  FN (missed gold): {'start': 0, 'end': 9, 'label': 'BIBLE_REF', 'text': 'Ayun 15-16 done'}

[40] "Besok daniel ulang tahun"
  FP (wrong pred) : {'start': 6, 'end': 12, 'label': 'BIBLE_REF', 'text': 'daniel'}

[42] "Zed 1-3 done"
  FN (missed gold): {'start': 0, 'end': 7, 'label': 'BIBLE_REF', 'text': 'Zed 1-3'}

[43] "Raja film 2 bagus banget"
  FP (wrong pred) : {'start': 5, 'end': 11, 'label': 'BIBLE_REF', 'text': 'film 2'}

[46] "Eps 3—4 done"
  FN (missed gold): {'start': 0, 'end': 7, 'label': 'BIBLE_REF', 'text': 'Eps 3—4'}

[47] "Kej 1 s/d 2 done"
  FP (wrong pred) : {'start': 0, 'end': 5, 'label': 'BIBLE_REF', 'text': 'Kej 1'}
  FN (missed gold): {'start': 0, 'end': 11, 'label': 'BIBLE_REF', 'text': 'Kej 1 s/d 2'}

[48] " Mikha 6/7 done"
  FP (wrong pred) : {'start': 0, 'end': 7, 'label': 'BIBLE_REF', 'text': 'Mikha 6'}
  FN (missed gold): {'start': 0, 'end': 9, 'label': 'BIBLE_REF', 'text': 'Mikha 6/7'}

[49] "2 Raja-blraja 6 - 7 done"
  FP (wrong pred) : {'start': 0, 'end': 6, 'label': 'BIBLE_REF', 'text': '2 Raja'}
  FN (missed gold): {'start': 0, 'end': 19, 'label': 'BIBLE_REF', 'text': '2 Raja-blraja 6 - 7'}

[50] "1kor1-3 done"
  FP (wrong pred) : {'start': 0, 'end': 9, 'label': 'BIBLE_REF', 'text': '1 kor 1-3'}
  FN (missed gold): {'start': 0, 'end': 7, 'label': 'BIBLE_REF', 'text': '1kor1-3'}

[51] "kej1 - 5done"
  FP (wrong pred) : {'start': 0, 'end': 9, 'label': 'BIBLE_REF', 'text': 'kej 1 - 5'}
  FN (missed gold): {'start': 0, 'end': 8, 'label': 'BIBLE_REF', 'text': 'kej1 - 5'}

[52] "Mas  23  done"
  FN (missed gold): {'start': 0, 'end': 6, 'label': 'BIBLE_REF', 'text': 'Maz 23'}

[54] "Estter 3 - 6 done"
  FN (missed gold): {'start': 0, 'end': 12, 'label': 'BIBLE_REF', 'text': 'Estter 3 - 6'}

[55] "Yea 61-64 done"
  FN (missed gold): {'start': 0, 'end': 9, 'label': 'BIBLE_REF', 'text': 'Yea 61-64'}

[57] "Rap 1-5 selesai"
  FN (missed gold): {'start': 0, 'end': 7, 'label': 'BIBLE_REF', 'text': 'Rap 1-5'}

[60] "Ķel 5-6 done"
  FN (missed gold): {'start': 0, 'end': 7, 'label': 'BIBLE_REF', 'text': 'Ķel 5-6'}

[61] "Mika 3-4 done"
  FN (missed gold): {'start': 0, 'end': 9, 'label': 'BIBLE_REF', 'text': 'Mika 3-4'}

[62] "_raт 1-2_ ✓"
  FN (missed gold): {'start': 1, 'end': 8, 'label': 'BIBLE_REF', 'text': '_raт 1-2_'}

[63] "Aayb 37-40 done"
  FN (missed gold): {'start': 0, 'end': 10, 'label': 'BIBLE_REF', 'text': 'Aayb 37-40'}

[64] "Krl 25-26 done"
  FN (missed gold): {'start': 0, 'end': 9, 'label': 'BIBLE_REF', 'text': 'Krl 25-26'}

[65] "Bilamgan 2-3 selesai"
  FN (missed gold): {'start': 0, 'end': 12, 'label': 'BIBLE_REF', 'text': 'Bilamgan 2-3'}

[66] "Nehemua 10-11 done"
  FN (missed gold): {'start': 0, 'end': 13, 'label': 'BIBLE_REF', 'text': 'Nehemua 10-11'}

[67] "Esra 1- 2 selesai.🙏"
  FN (missed gold): {'start': 0, 'end': 9, 'label': 'BIBLE_REF', 'text': 'Esra 1- 2'}

[68] "2 rajaraja 3-10 done"
  FN (missed gold): {'start': 0, 'end': 15, 'label': 'BIBLE_REF', 'text': '2 rajaraja 3-10'}

[69] "Haj 16-17 done"
  FN (missed gold): {'start': 0, 'end': 9, 'label': 'BIBLE_REF', 'text': 'Haj 16-17'}

[70] "Ruk 3-4 done"
  FN (missed gold): {'start': 0, 'end': 7, 'label': 'BIBLE_REF', 'text': 'Ruk 3-4'}

[71] "Ìmamat 15-18"
  FN (missed gold): {'start': 0, 'end': 12, 'label': 'BIBLE_REF', 'text': 'Ìmamat 15-18'}

[72] "1 Samurl 11-12 done"
  FN (missed gold): {'start': 0, 'end': 14, 'label': 'BIBLE_REF', 'text': '1 Samurl 11-12'}

[73] "I'm 23-27 done"
  FN (missed gold): {'start': 0, 'end': 9, 'label': 'BIBLE_REF', 'text': "I'm 23-27"}

[74] "Keh 47- 48 selesai 🙏"
  FN (missed gold): {'start': 0, 'end': 10, 'label': 'BIBLE_REF', 'text': 'Keh 47- 48'}

[75] "Pengk 1-8 done"
  FN (missed gold): {'start': 0, 'end': 9, 'label': 'BIBLE_REF', 'text': 'Pengk 1-8'}

[76] "Efrsus done"
  FN (missed gold): {'start': 0, 'end': 6, 'label': 'BIBLE_REF', 'text': 'Efrsus'}

[77] "Mxm 144-145 done"
  FN (missed gold): {'start': 0, 'end': 11, 'label': 'BIBLE_REF', 'text': 'Mxm 144-145'}

[78] "Habaguk 2-3 selesai🙏🏻"
  FN (missed gold): {'start': 0, 'end': 11, 'label': 'BIBLE_REF', 'text': 'Habaguk 2-3'}

[79] "Rima done"
  FN (missed gold): {'start': 0, 'end': 4, 'label': 'BIBLE_REF', 'text': 'Rima'}
============================================================
 CRF
============================================================

[2] "Efs1-2 done"
  FP (wrong pred) : {'start': 0, 'end': 7, 'label': 'BIBLE_REF', 'text': 'Efs 1-2'}
  FN (missed gold): {'start': 0, 'end': 6, 'label': 'BIBLE_REF', 'text': 'Efs1-2'}

[3] "_Bil 1-2_ ✓"
  FP (wrong pred) : {'start': 2, 'end': 9, 'label': 'BIBLE_REF', 'text': 'Bil 1-2'}
  FN (missed gold): {'start': 1, 'end': 8, 'label': 'BIBLE_REF', 'text': 'Bil 1-2'}

[19] "Amos, Obaja, Yunus, Mikha, Nahum, Habakuk, Zefanya, Hagai, Zakaria, Maleaki done"
  FN (missed gold): {'start': 0, 'end': 4, 'label': 'BIBLE_REF', 'text': 'Amos'}
  FN (missed gold): {'start': 6, 'end': 11, 'label': 'BIBLE_REF', 'text': 'Obaja'}
  FN (missed gold): {'start': 13, 'end': 18, 'label': 'BIBLE_REF', 'text': 'Yunus'}
  FN (missed gold): {'start': 20, 'end': 25, 'label': 'BIBLE_REF', 'text': 'Mikha'}
  FN (missed gold): {'start': 27, 'end': 32, 'label': 'BIBLE_REF', 'text': 'Nahum'}
  FN (missed gold): {'start': 34, 'end': 41, 'label': 'BIBLE_REF', 'text': 'Habakuk'}
  FN (missed gold): {'start': 43, 'end': 50, 'label': 'BIBLE_REF', 'text': 'Zefanya'}
  FN (missed gold): {'start': 52, 'end': 57, 'label': 'BIBLE_REF', 'text': 'Hagai'}
  FN (missed gold): {'start': 59, 'end': 66, 'label': 'BIBLE_REF', 'text': 'Zakaria'}

[24] "```Kidung Agung 5 - Kidung Agung 6```✅"
  FP (wrong pred) : {'start': 0, 'end': 37, 'label': 'BIBLE_REF', 'text': '```Kidung Agung 5 - Kidung Agung 6```'}
  FN (missed gold): {'start': 3, 'end': 34, 'label': 'BIBLE_REF', 'text': 'Kidung Agung 5 - Kidung Agung 6'}

[28] "1-2 Samuel selesai"
  FN (missed gold): {'start': 0, 'end': 10, 'label': 'BIBLE_REF', 'text': '1-2 Samuel'}

[31] "Kej 5-6 done
7-8 done
9-10 done"
  FP (wrong pred) : {'start': 13, 'end': 26, 'label': 'BIBLE_REF', 'text': '7-8 done 9-10'}
  FN (missed gold): {'start': 13, 'end': 16, 'label': 'BIBLE_REF', 'text': '7-8'}
  FN (missed gold): {'start': 22, 'end': 26, 'label': 'BIBLE_REF', 'text': '9-10'}

[35] "Ayun 15-16 done"
  FP (wrong pred) : {'start': 0, 'end': 10, 'label': 'BIBLE_REF', 'text': 'Ayun 15-16'}
  FN (missed gold): {'start': 0, 'end': 9, 'label': 'BIBLE_REF', 'text': 'Ayun 15-16 done'}

[37] "Saya sudah sampai Ul 36, terima kasih"
  FN (missed gold): {'start': 18, 'end': 23, 'label': 'BIBLE_REF', 'text': 'Ul 36'}

[38] "Bu Dessi, saya belum selesai baca Daniel 13"
  FN (missed gold): {'start': 34, 'end': 43, 'label': 'BIBLE_REF', 'text': 'Daniel 13'}

[43] "Raja film 2 bagus banget"
  FP (wrong pred) : {'start': 0, 'end': 11, 'label': 'BIBLE_REF', 'text': 'Raja film 2'}

[50] "1kor1-3 done"
  FP (wrong pred) : {'start': 0, 'end': 9, 'label': 'BIBLE_REF', 'text': '1 kor 1-3'}
  FN (missed gold): {'start': 0, 'end': 7, 'label': 'BIBLE_REF', 'text': '1kor1-3'}

[51] "kej1 - 5done"
  FP (wrong pred) : {'start': 0, 'end': 9, 'label': 'BIBLE_REF', 'text': 'kej 1 - 5'}
  FN (missed gold): {'start': 0, 'end': 8, 'label': 'BIBLE_REF', 'text': 'kej1 - 5'}

[56] "Wahyu ✓"
  FN (missed gold): {'start': 0, 'end': 5, 'label': 'BIBLE_REF', 'text': 'Wahyu'}

[61] "Mika 3-4 done"
  FP (wrong pred) : {'start': 0, 'end': 8, 'label': 'BIBLE_REF', 'text': 'Mika 3-4'}
  FN (missed gold): {'start': 0, 'end': 9, 'label': 'BIBLE_REF', 'text': 'Mika 3-4'}

[62] "_raт 1-2_ ✓"
  FP (wrong pred) : {'start': 2, 'end': 9, 'label': 'BIBLE_REF', 'text': 'raт 1-2'}
  FN (missed gold): {'start': 1, 'end': 8, 'label': 'BIBLE_REF', 'text': '_raт 1-2_'}
============================================================
 IndoBERT NER
============================================================

[2] "Efs1-2 done"
  FP (wrong pred) : {'start': 0, 'end': 7, 'label': 'BIBLE_REF', 'text': 'efs 1 - 2'}
  FN (missed gold): {'start': 0, 'end': 6, 'label': 'BIBLE_REF', 'text': 'Efs1-2'}

[3] "_Bil 1-2_ ✓"
  FP (wrong pred) : {'start': 2, 'end': 9, 'label': 'BIBLE_REF', 'text': 'bil 1 - 2'}
  FN (missed gold): {'start': 1, 'end': 8, 'label': 'BIBLE_REF', 'text': 'Bil 1-2'}

[19] "Amos, Obaja, Yunus, Mikha, Nahum, Habakuk, Zefanya, Hagai, Zakaria, Maleaki done"
  FP (wrong pred) : {'start': 0, 'end': 2, 'label': 'BIBLE_REF', 'text': 'am'}
  FP (wrong pred) : {'start': 43, 'end': 45, 'label': 'BIBLE_REF', 'text': 'ze'}
  FN (missed gold): {'start': 0, 'end': 4, 'label': 'BIBLE_REF', 'text': 'Amos'}
  FN (missed gold): {'start': 43, 'end': 50, 'label': 'BIBLE_REF', 'text': 'Zefanya'}

[35] "Ayun 15-16 done"
  FP (wrong pred) : {'start': 0, 'end': 10, 'label': 'BIBLE_REF', 'text': 'ayun 15 - 16'}
  FN (missed gold): {'start': 0, 'end': 9, 'label': 'BIBLE_REF', 'text': 'Ayun 15-16 done'}

[50] "1kor1-3 done"
  FP (wrong pred) : {'start': 0, 'end': 9, 'label': 'BIBLE_REF', 'text': '1 kor 1 - 3'}
  FN (missed gold): {'start': 0, 'end': 7, 'label': 'BIBLE_REF', 'text': '1kor1-3'}

[51] "kej1 - 5done"
  FP (wrong pred) : {'start': 0, 'end': 9, 'label': 'BIBLE_REF', 'text': 'kej 1 - 5'}
  FN (missed gold): {'start': 0, 'end': 8, 'label': 'BIBLE_REF', 'text': 'kej1 - 5'}

[61] "Mika 3-4 done"
  FP (wrong pred) : {'start': 0, 'end': 8, 'label': 'BIBLE_REF', 'text': 'mika 3 - 4'}
  FN (missed gold): {'start': 0, 'end': 9, 'label': 'BIBLE_REF', 'text': 'Mika 3-4'}

[62] "_raт 1-2_ ✓"
  FP (wrong pred) : {'start': 2, 'end': 9, 'label': 'BIBLE_REF', 'text': 'raт 1 - 2'}
  FN (missed gold): {'start': 1, 'end': 8, 'label': 'BIBLE_REF', 'text': '_raт 1-2_'}

In [12]:
# structural error analysis
error_analysis('Regex (baseline)', regex_structs, gold_structs, gold_data, struct_exact_match)
error_analysis('CRF', crf_structs, gold_structs, gold_data, struct_exact_match)
error_analysis('IndoBERT NER', ner_structs, gold_structs, gold_data, struct_exact_match)

============================================================
 Regex (baseline)
============================================================

[0] "2 Yuhanes done"
  FN (missed gold): {'book_start': '2 Yuhanes', 'start_chapter': None, 'book_end': None, 'end_chapter': None}

[5] "2 Koruntus done"
  FN (missed gold): {'book_start': '2 Koruntus', 'start_chapter': None, 'book_end': None, 'end_chapter': None}

[12] "Ibrani 11-Yakobus 1; 2-3; 4-5"
  FN (missed gold): {'book_start': 'Yakobus', 'start_chapter': 2, 'book_end': None, 'end_chapter': 3}
  FN (missed gold): {'book_start': 'Yakobus', 'start_chapter': 4, 'book_end': None, 'end_chapter': 5}

[15] "1 Kor 1,2,3,4,5 done"
  FN (missed gold): {'book_start': '1 Kor', 'start_chapter': 2, 'book_end': None, 'end_chapter': None}
  FN (missed gold): {'book_start': '1 Kor', 'start_chapter': 3, 'book_end': None, 'end_chapter': None}
  FN (missed gold): {'book_start': '1 Kor', 'start_chapter': 4, 'book_end': None, 'end_chapter': None}
  FN (missed gold): {'book_start': '1 Kor', 'start_chapter': 5, 'book_end': None, 'end_chapter': None}

[16] "Mazmur 1, 23, 91 selesai"
  FN (missed gold): {'book_start': 'Mazmur', 'start_chapter': 23, 'book_end': None, 'end_chapter': None}
  FN (missed gold): {'book_start': 'Mazmur', 'start_chapter': 91, 'book_end': None, 'end_chapter': None}

[17] "Mat 5, 6, 7 done"
  FN (missed gold): {'book_start': 'Mat', 'start_chapter': 6, 'book_end': None, 'end_chapter': None}
  FN (missed gold): {'book_start': 'Mat', 'start_chapter': 7, 'book_end': None, 'end_chapter': None}

[18] "Kej 1,3,5,7 selesai"
  FN (missed gold): {'book_start': 'Kej', 'start_chapter': 3, 'book_end': None, 'end_chapter': None}
  FN (missed gold): {'book_start': 'Kej', 'start_chapter': 5, 'book_end': None, 'end_chapter': None}
  FN (missed gold): {'book_start': 'Kej', 'start_chapter': 7, 'book_end': None, 'end_chapter': None}

[23] "hakim-hakim 6 - hakim-hakim 7 selesai"
  FP (wrong pred) : {'book_start': 'hakim-hakim', 'start_chapter': 6, 'book_end': 'hakim-hakim', 'end_chapter': 7}
  FN (missed gold): {'book_start': 'hakim-hakim', 'start_chapter': 6, 'book_end': None, 'end_chapter': 7}

[24] "```Kidung Agung 5 - Kidung Agung 6```✅"
  FP (wrong pred) : {'book_start': 'Kidung Agung', 'start_chapter': 5, 'book_end': 'Kidung Agung', 'end_chapter': 6}
  FN (missed gold): {'book_start': 'Kidung Agung', 'start_chapter': 5, 'book_end': None, 'end_chapter': 6}

[26] "1-3 Yoh done"
  FP (wrong pred) : {'book_start': '3 Yoh', 'start_chapter': None, 'book_end': None, 'end_chapter': None}
  FN (missed gold): {'book_start': '1 Yoh', 'start_chapter': None, 'book_end': '3 Yoh', 'end_chapter': None}

[27] "1-2 Kor done"
  FP (wrong pred) : {'book_start': '2 Kor', 'start_chapter': None, 'book_end': None, 'end_chapter': None}
  FN (missed gold): {'book_start': '1 Kor', 'start_chapter': None, 'book_end': '2 Kor', 'end_chapter': None}

[28] "1-2 Samuel selesai"
  FP (wrong pred) : {'book_start': '2 Samuel', 'start_chapter': None, 'book_end': None, 'end_chapter': None}
  FN (missed gold): {'book_start': '1 Samuel', 'start_chapter': None, 'book_end': '2 Samuel', 'end_chapter': None}

[31] "Kej 5-6 done
7-8 done
9-10 done"
  FN (missed gold): {'book_start': 'Kej', 'start_chapter': 7, 'book_end': None, 'end_chapter': 8}
  FN (missed gold): {'book_start': 'Kej', 'start_chapter': 9, 'book_end': None, 'end_chapter': 10}

[34] "Msm 13 - 14 done"
  FN (missed gold): {'book_start': 'Msm', 'start_chapter': 13, 'book_end': None, 'end_chapter': 14}

[35] "Ayun 15-16 done"
  FN (missed gold): {'book_start': 'Ayun', 'start_chapter': 15, 'book_end': None, 'end_chapter': 16}

[40] "Besok daniel ulang tahun"
  FP (wrong pred) : {'book_start': 'daniel', 'start_chapter': None, 'book_end': None, 'end_chapter': None}

[42] "Zed 1-3 done"
  FN (missed gold): {'book_start': 'Zed', 'start_chapter': 1, 'book_end': None, 'end_chapter': 3}

[43] "Raja film 2 bagus banget"
  FP (wrong pred) : {'book_start': 'film', 'start_chapter': 2, 'book_end': None, 'end_chapter': None}

[46] "Eps 3—4 done"
  FN (missed gold): {'book_start': 'Eps', 'start_chapter': 3, 'book_end': None, 'end_chapter': 4}

[47] "Kej 1 s/d 2 done"
  FP (wrong pred) : {'book_start': 'Kej', 'start_chapter': 1, 'book_end': None, 'end_chapter': None}
  FN (missed gold): {'book_start': 'Kej', 'start_chapter': 1, 'book_end': None, 'end_chapter': 2}

[48] " Mikha 6/7 done"
  FN (missed gold): {'book_start': 'Mikha', 'start_chapter': 7, 'book_end': None, 'end_chapter': None}

[49] "2 Raja-blraja 6 - 7 done"
  FP (wrong pred) : {'book_start': '2 Raja', 'start_chapter': None, 'book_end': None, 'end_chapter': None}
  FN (missed gold): {'book_start': '2 Raja-blraja', 'start_chapter': 6, 'book_end': None, 'end_chapter': 7}

[52] "Mas  23  done"
  FN (missed gold): {'book_start': 'Mas', 'start_chapter': 23, 'book_end': None, 'end_chapter': None}

[54] "Estter 3 - 6 done"
  FN (missed gold): {'book_start': 'Estter', 'start_chapter': 3, 'book_end': None, 'end_chapter': 6}

[55] "Yea 61-64 done"
  FN (missed gold): {'book_start': 'Yea', 'start_chapter': 61, 'book_end': None, 'end_chapter': 64}

[57] "Rap 1-5 selesai"
  FN (missed gold): {'book_start': 'Rap', 'start_chapter': 1, 'book_end': None, 'end_chapter': 5}

[60] "Ķel 5-6 done"
  FN (missed gold): {'book_start': 'Ķel', 'start_chapter': 5, 'book_end': None, 'end_chapter': 6}

[61] "Mika 3-4 done"
  FN (missed gold): {'book_start': 'Mikha', 'start_chapter': 17, 'book_end': None, 'end_chapter': 18}

[62] "_raт 1-2_ ✓"
  FN (missed gold): {'book_start': 'raт', 'start_chapter': 1, 'book_end': None, 'end_chapter': 2}

[63] "Aayb 37-40 done"
  FN (missed gold): {'book_start': 'Aayb', 'start_chapter': 37, 'book_end': None, 'end_chapter': 40}

[64] "Krl 25-26 done"
  FN (missed gold): {'book_start': 'Krl', 'start_chapter': 25, 'book_end': None, 'end_chapter': 26}

[65] "Bilamgan 2-3 selesai"
  FN (missed gold): {'book_start': 'Bilamgan', 'start_chapter': 2, 'book_end': None, 'end_chapter': 3}

[66] "Nehemua 10-11 done"
  FN (missed gold): {'book_start': 'Nehemua', 'start_chapter': 10, 'book_end': None, 'end_chapter': 11}

[67] "Esra 1- 2 selesai.🙏"
  FN (missed gold): {'book_start': 'Esra', 'start_chapter': 1, 'book_end': None, 'end_chapter': 2}

[68] "2 rajaraja 3-10 done"
  FN (missed gold): {'book_start': '2 rajaraja', 'start_chapter': 3, 'book_end': None, 'end_chapter': 10}

[69] "Haj 16-17 done"
  FN (missed gold): {'book_start': 'Haj', 'start_chapter': 16, 'book_end': None, 'end_chapter': 17}

[70] "Ruk 3-4 done"
  FN (missed gold): {'book_start': 'Ruk', 'start_chapter': 3, 'book_end': None, 'end_chapter': 4}

[71] "Ìmamat 15-18"
  FN (missed gold): {'book_start': 'Ìmamat', 'start_chapter': 15, 'book_end': None, 'end_chapter': 18}

[72] "1 Samurl 11-12 done"
  FN (missed gold): {'book_start': '1 Samurl', 'start_chapter': 11, 'book_end': None, 'end_chapter': 12}

[73] "I'm 23-27 done"
  FN (missed gold): {'book_start': "I'm", 'start_chapter': 23, 'book_end': None, 'end_chapter': 27}

[74] "Keh 47- 48 selesai 🙏"
  FN (missed gold): {'book_start': 'Keh', 'start_chapter': 47, 'book_end': None, 'end_chapter': 48}

[75] "Pengk 1-8 done"
  FN (missed gold): {'book_start': 'Pengk', 'start_chapter': 1, 'book_end': None, 'end_chapter': 8}

[76] "Efrsus done"
  FN (missed gold): {'book_start': 'Efrsus', 'start_chapter': None, 'book_end': None, 'end_chapter': None}

[77] "Mxm 144-145 done"
  FN (missed gold): {'book_start': 'Mxm', 'start_chapter': 144, 'book_end': None, 'end_chapter': 145}

[78] "Habaguk 2-3 selesai🙏🏻"
  FN (missed gold): {'book_start': 'Habaguk', 'start_chapter': 2, 'book_end': None, 'end_chapter': 3}

[79] "Rima done"
  FN (missed gold): {'book_start': 'Rima', 'start_chapter': None, 'book_end': None, 'end_chapter': None}
============================================================
 CRF
============================================================

[19] "Amos, Obaja, Yunus, Mikha, Nahum, Habakuk, Zefanya, Hagai, Zakaria, Maleaki done"
  FN (missed gold): {'book_start': 'Amos', 'start_chapter': None, 'book_end': None, 'end_chapter': None}
  FN (missed gold): {'book_start': 'Obaja', 'start_chapter': None, 'book_end': None, 'end_chapter': None}
  FN (missed gold): {'book_start': 'Yunus', 'start_chapter': None, 'book_end': None, 'end_chapter': None}
  FN (missed gold): {'book_start': 'Mikha', 'start_chapter': None, 'book_end': None, 'end_chapter': None}
  FN (missed gold): {'book_start': 'Nahum', 'start_chapter': None, 'book_end': None, 'end_chapter': None}
  FN (missed gold): {'book_start': 'Habakuk', 'start_chapter': None, 'book_end': None, 'end_chapter': None}
  FN (missed gold): {'book_start': 'Zefanya', 'start_chapter': None, 'book_end': None, 'end_chapter': None}
  FN (missed gold): {'book_start': 'Hagai', 'start_chapter': None, 'book_end': None, 'end_chapter': None}
  FN (missed gold): {'book_start': 'Zakaria', 'start_chapter': None, 'book_end': None, 'end_chapter': None}

[28] "1-2 Samuel selesai"
  FN (missed gold): {'book_start': '1 Samuel', 'start_chapter': None, 'book_end': '2 Samuel', 'end_chapter': None}

[31] "Kej 5-6 done
7-8 done
9-10 done"
  FP (wrong pred) : {'book_start': '7 done', 'start_chapter': None, 'book_end': '8 done', 'end_chapter': None}
  FP (wrong pred) : {'book_start': '8 done', 'start_chapter': 9, 'book_end': None, 'end_chapter': 10}
  FN (missed gold): {'book_start': 'Kej', 'start_chapter': 7, 'book_end': None, 'end_chapter': 8}
  FN (missed gold): {'book_start': 'Kej', 'start_chapter': 9, 'book_end': None, 'end_chapter': 10}

[37] "Saya sudah sampai Ul 36, terima kasih"
  FN (missed gold): {'book_start': 'Ul', 'start_chapter': 36, 'book_end': None, 'end_chapter': None}

[38] "Bu Dessi, saya belum selesai baca Daniel 13"
  FN (missed gold): {'book_start': 'Daniel', 'start_chapter': 13, 'book_end': None, 'end_chapter': None}

[43] "Raja film 2 bagus banget"
  FP (wrong pred) : {'book_start': 'raja film', 'start_chapter': 2, 'book_end': None, 'end_chapter': None}

[56] "Wahyu ✓"
  FN (missed gold): {'book_start': 'Wahyu', 'start_chapter': None, 'book_end': None, 'end_chapter': None}

[60] "Ķel 5-6 done"
  FP (wrong pred) : {'book_start': 'el', 'start_chapter': 5, 'book_end': None, 'end_chapter': 6}
  FN (missed gold): {'book_start': 'Ķel', 'start_chapter': 5, 'book_end': None, 'end_chapter': 6}

[61] "Mika 3-4 done"
  FP (wrong pred) : {'book_start': 'mika', 'start_chapter': 3, 'book_end': None, 'end_chapter': 4}
  FN (missed gold): {'book_start': 'Mikha', 'start_chapter': 17, 'book_end': None, 'end_chapter': 18}

[62] "_raт 1-2_ ✓"
  FP (wrong pred) : {'book_start': 'ra', 'start_chapter': 1, 'book_end': None, 'end_chapter': 2}
  FN (missed gold): {'book_start': 'raт', 'start_chapter': 1, 'book_end': None, 'end_chapter': 2}

[71] "Ìmamat 15-18"
  FP (wrong pred) : {'book_start': 'mamat', 'start_chapter': 15, 'book_end': None, 'end_chapter': 18}
  FN (missed gold): {'book_start': 'Ìmamat', 'start_chapter': 15, 'book_end': None, 'end_chapter': 18}

[73] "I'm 23-27 done"
  FP (wrong pred) : {'book_start': 'i m', 'start_chapter': 23, 'book_end': None, 'end_chapter': 27}
  FN (missed gold): {'book_start': "I'm", 'start_chapter': 23, 'book_end': None, 'end_chapter': 27}
============================================================
 IndoBERT NER
============================================================

[19] "Amos, Obaja, Yunus, Mikha, Nahum, Habakuk, Zefanya, Hagai, Zakaria, Maleaki done"
  FP (wrong pred) : {'book_start': 'am', 'start_chapter': None, 'book_end': None, 'end_chapter': None}
  FP (wrong pred) : {'book_start': 'ze', 'start_chapter': None, 'book_end': None, 'end_chapter': None}
  FN (missed gold): {'book_start': 'Amos', 'start_chapter': None, 'book_end': None, 'end_chapter': None}
  FN (missed gold): {'book_start': 'Zefanya', 'start_chapter': None, 'book_end': None, 'end_chapter': None}

[60] "Ķel 5-6 done"
  FP (wrong pred) : {'book_start': 'kel', 'start_chapter': 5, 'book_end': None, 'end_chapter': 6}
  FN (missed gold): {'book_start': 'Ķel', 'start_chapter': 5, 'book_end': None, 'end_chapter': 6}

[61] "Mika 3-4 done"
  FP (wrong pred) : {'book_start': 'mika', 'start_chapter': 3, 'book_end': None, 'end_chapter': 4}
  FN (missed gold): {'book_start': 'Mikha', 'start_chapter': 17, 'book_end': None, 'end_chapter': 18}

[62] "_raт 1-2_ ✓"
  FP (wrong pred) : {'book_start': 'ra', 'start_chapter': 1, 'book_end': None, 'end_chapter': 2}
  FN (missed gold): {'book_start': 'raт', 'start_chapter': 1, 'book_end': None, 'end_chapter': 2}

[71] "Ìmamat 15-18"
  FP (wrong pred) : {'book_start': 'imamat', 'start_chapter': 15, 'book_end': None, 'end_chapter': 18}
  FN (missed gold): {'book_start': 'Ìmamat', 'start_chapter': 15, 'book_end': None, 'end_chapter': 18}

[73] "I'm 23-27 done"
  FP (wrong pred) : {'book_start': 'i m', 'start_chapter': 23, 'book_end': None, 'end_chapter': 27}
  FN (missed gold): {'book_start': "I'm", 'start_chapter': 23, 'book_end': None, 'end_chapter': 27}

---
## 9. Confidence Intervals

Bootstrap resampling (1,000 iterations) over the test set to estimate F1 stability and verify that performance differences between models are reliable.

In [13]:
def bootstrap_ci(pred_structs, gold_structs, match_fn, n_iterations=1000, ci=0.95):
    indices = list(range(len(gold_structs)))
    f1_scores = []

    for _ in range(n_iterations):
        sample = np.random.choice(indices, size=len(indices), replace=True)
        sampled_preds = [pred_structs[i] for i in sample]
        sampled_golds = [gold_structs[i] for i in sample]

        result = compute_prf(sampled_preds, sampled_golds, match_fn)
        f1_scores.append(result['f1'])

    alpha = 1 - ci
    lower = np.percentile(f1_scores, 100 * (alpha / 2))
    upper = np.percentile(f1_scores, 100 * (1 - alpha / 2))
    return lower, upper

models = [
    ('Regex (baseline)', regex_spans, regex_structs),
    ('CRF', crf_spans, crf_structs),
    ('IndoBERT NER', ner_spans, ner_structs)
]

np.random.seed(42)
print(f"{'Model':<20} {'Metric':<20} {'F1':>6}  {'95% CI'}")
print('-' * 60)
for name, pred_spans, pred_structs in models:
    for label, match_fn, preds, golds in [
        ('Spans Exact', span_exact_match, pred_spans, gold_spans), 
        ('Spans Partial', span_partial_match, pred_spans, gold_spans), 
        ('Structural', struct_exact_match, pred_structs, gold_structs),
    ]:
        result = compute_prf(preds, golds, match_fn)
        lo, hi = bootstrap_ci(preds, golds, match_fn)
        print(f"{name:<20} {label:<20} {result['f1']:.4f}  [{lo:.4f}, {hi:.4f}]")

Model                Metric                   F1  95% CI
------------------------------------------------------------
Regex (baseline)     Spans Exact          0.6190  [0.4730, 0.7426]
Regex (baseline)     Spans Partial        0.7976  [0.7007, 0.8701]
Regex (baseline)     Structural           0.6593  [0.5432, 0.7604]
CRF                  Spans Exact          0.8216  [0.7182, 0.9167]
CRF                  Spans Partial        0.9189  [0.8204, 0.9840]
CRF                  Structural           0.8692  [0.7802, 0.9484]
IndoBERT NER         Spans Exact          0.9091  [0.8511, 0.9655]
IndoBERT NER         Spans Partial        1.0000  [1.0000, 1.0000]
IndoBERT NER         Structural           0.9381  [0.8877, 0.9815]